language: go
go:
  - 1.x
before_install:
  - go get -v github.com/BurntSushi/toml gopkg.in/ldap.v2
script:
  - go test
after_success:
  - test -n "$TRAVIS_TAG" && curl -sL https://git.io/goreleaser | bash